AWS_ACCESS_KEY_ID = "AKIA6IY356VO7X276TXY"
AWS_SECRET_ACCESS_KEY = "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"
AWS_REGION = "us-east-1"
SNS_TOPIC_ARN = "arn:aws:sns:us-east-1:980921742685:gstreminder"
